#!/usr/bin/env python3
"""docs/CLI.md from the CLI's own usage text (FableForge --help), so the reference
never drifts from main.cpp. Run after adding a command:

  python tools/gen_cli_reference.py
"""
import os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main() -> int:
    cli = os.path.join(ROOT, "build", "forge.exe")
    r = subprocess.run([cli, "--help"], capture_output=True, text=True)
    text = (r.stdout + r.stderr).strip()
    if not text:
        print("no usage text (build first)"); return 1
    lines = text.splitlines()
    title = lines[0]
    body = "\n".join(lines[1:])
    out = ["# Command line reference", "",
           f"`{title}`", "",
           "Generated by `tools/gen_cli_reference.py` from `FableForge --help`; edit `src/main.cpp`'s usage text, not this file.",
           "Every command takes `--install <fable-root>` (default: the Steam / GOG install found on this machine).",
           "Commands that write game files keep a one-time `<file>.forge-orig` backup and are refused while Fable runs.",
           "", "```text", body, "```", ""]
    with open(os.path.join(ROOT, "docs", "CLI.md"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print("wrote docs/CLI.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
