#!/usr/bin/env python3
"""src/vanilla_props.inc from docs/re_reference/vanilla_property_fields.tsv.

The TSV maps the vanilla editor's Thing Properties entries (FableWin
GetPropertiesStruct per class, static RE) to the .tng key each one edits, with
the dialog's widget kind, def type / enum values and numeric range. The property
grid shows the vanilla label and offers the matching picker from this table.
Run after editing the TSV:  python tools/gen_vanilla_props.py
"""
import csv, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "docs", "re_reference", "vanilla_property_fields.tsv")
OUT = os.path.join(ROOT, "src", "vanilla_props.inc")


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    rows = []
    rows_label = []
    seen = {}   # (ctc, key) -> index in rows: rows sharing a key (Colour <- ColourRed/Green/Blue) merge labels
    with open(SRC, encoding="utf-8", newline="") as f:
        for r in csv.DictReader(f, delimiter="\t"):
            key = (r.get("tng_key") or "").strip()
            if not key or "[" in key:   # list fields (CreatureFamilies[n]) are not single keys
                continue
            kind = (r.get("kind") or "").strip()
            defType = (r.get("def_type_or_enum") or "").strip()
            extra = (r.get("enum_values") or "").strip()
            lo = hi = step = "0"
            has_range = "false"
            m = re.search(r"range=([-0-9.eE]+)\.\.([-0-9.eE]+)(?:;step=([-0-9.eE]+))?", extra)
            if m:
                lo, hi, step = m.group(1), m.group(2), m.group(3) or "0"
                has_range = "true"
            enum = ""
            if kind == "enum" and "=" in extra and "range=" not in extra:
                enum = ";".join(p.strip() for p in extra.split(";") if re.match(r"^\s*[A-Za-z_][A-Za-z0-9_ ]*\s*=\s*-?\d+\s*$", p))
                if not enum:
                    kind = "string"      # a symbol list we cannot enumerate offline (particle names)
            if kind == "def" and " " in defType:
                defType = defType.split(" ")[0]
            ident = (r["ctc_block"].strip(), key)
            if ident in seen:
                i = seen[ident]
                rows[i] = rows[i].replace(cstr(rows_label[i]), cstr(rows_label[i] + " / " + r["label"].strip()), 1)
                rows_label[i] += " / " + r["label"].strip()
                continue
            seen[ident] = len(rows)
            rows_label.append(r["label"].strip())
            rows.append("    {%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s}," % (
                cstr(r["ctc_block"].strip()), cstr(key), cstr(r["category"].strip()), cstr(r["label"].strip()),
                cstr(kind), cstr(defType if kind == "def" else ""), cstr(enum),
                has_range, lo, hi, step, cstr((r.get("confidence") or "").strip())))
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Generated by tools/gen_vanilla_props.py from docs/re_reference/vanilla_property_fields.tsv -- do not edit.\n")
        f.write("// { ctc, tngKey, category, label, kind, defType, enumPairs, hasRange, min, max, step, confidence }\n")
        f.write("\n".join(rows) + "\n")
    print(f"wrote {OUT}: {len(rows)} fields")
    return 0


if __name__ == "__main__":
    sys.exit(main())
